server:
  port: 8001

mybatis:
  type-aliases-package: com.orange.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: spring-cloud-equitment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456789

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


management:
  endpoints:
    web:
      exposure:
        include: '*'